// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadStatus is a download's lifecycle state on the wire. These constants
 * mirror internal/engine's Status values as plain strings but are declared here
 * so the CLI never transitively imports the engine. They can drift if the
 * engine gains a status; the daemon's engine->view mapping is the single place
 * that must be updated to reflect such a change.
 */
export enum DownloadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusActive = "active",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusFailed = "failed",
};

/**
 * DownloadView is the pure-data projection of a download returned by status and
 * list. It is deliberately not engine.Download: keeping a separate, flat view
 * keeps this package a leaf and lets the wire shape evolve independently of the
 * engine's internal model.
 */
export class DownloadView {
    "id": string;
    "url": string;
    "status": DownloadStatus;
    "priority": Priority;
    "total_size": number;
    "downloaded": number;

    /**
     * SpeedBps is the live transfer rate in bytes/sec (0 when not downloading).
     * EtaSecs is the estimated seconds remaining, or -1 when unknown (no live rate
     * or unknown total). Both are server-computed so every client shows the same
     * value rather than each deriving its own from poll deltas.
     */
    "speed_bps": number;
    "eta_secs": number;
    "destination": string;

    /** Creates a new DownloadView instance. */
    constructor($$source: Partial<DownloadView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DownloadStatus.$zero;
        }
        if (!("priority" in $$source)) {
            this["priority"] = Priority.$zero;
        }
        if (!("total_size" in $$source)) {
            this["total_size"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("speed_bps" in $$source)) {
            this["speed_bps"] = 0;
        }
        if (!("eta_secs" in $$source)) {
            this["eta_secs"] = 0;
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadView instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadView($$parsedSource as Partial<DownloadView>);
    }
}

/**
 * Priority is a download's scheduling priority on the wire. Like DownloadStatus
 * it mirrors internal/engine's Priority as plain strings so the CLI never imports
 * the engine; the daemon's engine<->view mapping is the single translation point.
 * The empty string is treated as PriorityNormal, so a client that omits priority
 * (and an older client unaware of the field) keeps working.
 */
export enum Priority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PriorityLow = "low",
    PriorityNormal = "normal",
    PriorityHigh = "high",
};
