// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadStatus is a download's lifecycle state on the wire. These constants
 * mirror internal/engine's Status values as plain strings but are declared here
 * so the CLI never transitively imports the engine. They can drift if the
 * engine gains a status; the daemon's engine->view mapping is the single place
 * that must be updated to reflect such a change.
 */
export enum DownloadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusActive = "active",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusFailed = "failed",
};

/**
 * DownloadView is the pure-data projection of a download returned by status and
 * list. It is deliberately not engine.Download: keeping a separate, flat view
 * keeps this package a leaf and lets the wire shape evolve independently of the
 * engine's internal model.
 */
export interface DownloadView {
    "id": string;
    "url": string;
    "status": DownloadStatus;
    "priority": Priority;
    "total_size": number;
    "downloaded": number;

    /**
     * SpeedBps is the live transfer rate in bytes/sec (0 when not downloading).
     * EtaSecs is the estimated seconds remaining, or -1 when unknown (no live rate
     * or unknown total). Both are server-computed so every client shows the same
     * value rather than each deriving its own from poll deltas.
     */
    "speed_bps": number;
    "eta_secs": number;
    "destination": string;

    /**
     * The fields below are optional detail, populated for the properties view and
     * (for Segments) the per-connection progress display. They are omitempty so the
     * common list payload stays lean and older clients that ignore them are unaffected.
     * e.g. "sha256:…", empty when none
     */
    "checksum"?: string;

    /**
     * parallel connections planned
     */
    "segment_count"?: number;

    /**
     * RFC3339, empty when zero
     */
    "created_at"?: string;

    /**
     * RFC3339, empty when zero
     */
    "updated_at"?: string;

    /**
     * Segments carries each connection's byte range and live progress (IDM-style
     * "download progress by connections"). To keep the polled list lean it is
     * included only for in-flight downloads there; the status endpoint always
     * includes it.
     */
    "segments"?: SegmentView[] | null;
}

/**
 * Priority is a download's scheduling priority on the wire. Like DownloadStatus
 * it mirrors internal/engine's Priority as plain strings so the CLI never imports
 * the engine; the daemon's engine<->view mapping is the single translation point.
 * The empty string is treated as PriorityNormal, so a client that omits priority
 * (and an older client unaware of the field) keeps working.
 */
export enum Priority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PriorityLow = "low",
    PriorityNormal = "normal",
    PriorityHigh = "high",
};

/**
 * SegmentView is one parallel connection's byte range and live downloaded count.
 * Completed is the live, in-flight byte total for an active download (the daemon
 * folds the worker counters in before projecting), so a client can show each
 * connection's progress as Completed/(End-Start+1).
 */
export interface SegmentView {
    "index": number;

    /**
     * inclusive
     */
    "start": number;

    /**
     * inclusive
     */
    "end": number;

    /**
     * bytes written within the range
     */
    "completed": number;
}
